services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: backend-receitas-api
    restart: unless-stopped
    ports:
      - '3000:3000'
    env_file:
      - .env
    environment:
      DB_HOST: mysql
      DB_PORT: 3306
    depends_on:
      mysql:
        condition: service_healthy
    volumes:
      - ./:/app
      - /app/node_modules
      - setup_lock:/app/.setup-lock

  mysql:
    image: mysql:8.0
    container_name: backend-receitas-mysql
    restart: unless-stopped
    ports:
      - '3307:3306'
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_AUTHENTICATION_PLUGIN: caching_sha2_password
    healthcheck:
      test:
        ['CMD-SHELL', 'mysqladmin ping -h localhost -p$$MYSQL_ROOT_PASSWORD']
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 20s
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
  setup_lock:
